[stripe]
# Get these from your Stripe Dashboard
secret_key = "sk_test_51R5fjpFd1wTdLDf2GvzFSr5pjBrpTInuaweda8TY1fhMIOCPEZBemkbgGFTkGNY0z6Tzu4IAfrbnKdYQRvJX3jFg00K5zKT7eA"
publishable_key = "pk_test_51R5fjpFd1wTdLDf2id1lyamKIgFO6vXAAmUKz0WCCuUGVeRyJE2oZmlpMw7jW9cgi2ztN5UOaXLqbL8JNbyBDnPC00CuKCIEeK"
webhook_secret = "whsec_..." 